- hosts: bastion
  gather_facts: true

#- import_playbook: deploy_three_tier_app.yml
  tasks:
  - name: test app is up
    uri:
      url: http://"{% for host in groups['frontends'] %}{{ hostvars[host]['ansible_eth0']['ipv4']['address'] }}{% endfor %}"
      status_code: 200
  