---
# tasks file for aws facts
   - name: Fetch Instance Info
     ec2_instance_facts:
       region: us-east-1
       filters: tag:owner=pcarey*
     register: result
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.tag_Name }}"
      # ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      # ansible_ssh_user: cloud-user
     with_items: "{{ec2.instances}}"
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.three_tier_app* }}"
      #      ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      #  ansible_ssh_user: cloud-user
     with_items: "{{ec2.instances}}"
