
- hosts: frontends
  gather_facts: true

#- import_playbook: deploy_three_tier_app.yml
#- hosts: bastion
  tasks:
  - name: test app is up
    uri:
      url: http://{{ ansible_eth0["ipv4"]["address"] }}
      status_code: 200
      return_content: yes
  
