---
- hosts: jumpbox

  tasks:
  - degug:
    msg: "{% for host in groups['frontends'] %} {{ hostvars[host] }} {% endfor %}"

  - name: test app is up
    uri:
      url: "{% for host in groups['frontends'] %}
        {{ hostvars[host]['host_name'] }}
        {% endfor %}"
      status_code: 200
      return_content: yes