---
- hosts: frontends
  tasks:
  - debug:
    msg: "{% for host in groups['frontends'] %} {{ hostvars[host]['inventory_hostname'] }} {% endfor %}"

  - name: test app is up
    uri:
      url: "{% for host in groups['frontends'] %}
        {{ [host] }}
        {% endfor %}"
      status_code: 200
      return_content: yes
    ignore_errors: yes