---
- hosts: frontends
  tasks:
  - debug:
    var: hostvars[inventory_hostname]

  - name: test app is up
    uri:
      url: http://{{ hostname }}
      status_code: 200
      return_content: yes
    ignore_errors: yes