---
- name: dump all
  hosts: all
 
  tasks:
  - name: get variables
    debug:
var: hostvars[inventory_hostname]

- hosts: jumpbox

  tasks:
  - debug:
    msg: "{% for host in groups['frontends'] %} {{ hostvars[host]['item'] }} {% endfor %}"

  - name: test app is up
    uri:
      url: "{% for host in groups['frontends'] %}
        {{ hostvars[host]['host_name'] }}
        {% endfor %}"
      status_code: 200
      return_content: yes