---
- hosts: jumpbox

  tasks:
  - debug:
    msg: "{% for host in group['frontends'] %} {{ hostvars[host]['item'] }} {% endfor %}"

  - name: test app is up
    uri:
      url: "{% for host in group['frontends'] %}
        {{ hostvars[host]['host_name'] }}
        {% endfor %}"
      status_code: 200
      return_content: yes