---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: dummy task
      setup:

  roles:
    - { role: create_auth }
              #- import_playbook: aws/main.yml
              #
              #

