# Simple example relying on the default Postgres PUBLIC privileges
# which allow access to all users
#- hosts: localhost
- role: geerlingguy.postgresql
          become: yes


#- name: ensure latest postgres is present.
#  package:
#    name: postgresql-server
#    state: latest

#- name: enable postgres service and start
#  service:
#    name: postgresql
#    enabled: yes
#    state: started
