- name: ensure package httpie present and latest.
  package:
    name: httpie
    state: latest

- name: ensure package HAProxy present and latest.
  package:
    name: haproxy
    state: latest

- name: start and enable HAProxy service
  service:
    name: haproxy
    state: started
    enabled: yes
